glzr-io/zebar

packages/client-api/src/providers/glazewm/create-glazewm-provider.ts
Add FOCUS_CHANGED to subscribed events in create-glazewm-provider, which addresses active workspace not updating when navigating to other workspaces.
Sort workspaces by name numerically to organise workspaces in ascending order in bar when they have default/number names.
Fixes #30
=> fix: update glazewm workspaces on focus changes; order workspaces by number

packages/client-api/src/desktop/monitors.ts, packages/client-api/src/providers/glazewm/create-glazewm-provider.ts, packages/client-api/src/providers/komorebi/create-komorebi-provider.ts
=> feat: glazewm and komorebi providers update on window move/resize

.gitignore, packages/client-api/src/providers/komorebi/create-komorebi-provider.ts, packages/desktop/Cargo.toml, packages/desktop/src/providers/komorebi/provider.rs, packages/desktop/src/providers/komorebi/variables.rs
I intend to address an issue that is now fixed with Komorebi and Stackbar, as @LGUG2Z was kind enough to create a new release when this issue was fixed, just to make things faster.
This also helps those who upgrade Komorebi to a higher version compared to what is currently being used by Zebar, see #52.
=> chore: upgrade Komorebi client to v0.1.26

packages/client/package.json, packages/client/src/app/template-element.component.ts, pnpm-lock.yaml
Today, there's an issue with the logic around Zebar templates and how they are updated in the DOM. The current implementation replaces the `innerHTML` of the template node with the updated HTML from the templating engine.
This causes several issues, the most notable one being that it messes with CSS animations, which with the current implementation cannot have an "out"-animation for stuff like hover or classname toggling since the entire element is removed and re-inserted into the DOM - the "in" animation happens instead.
The solution to this, as well as a more efficient way to solve re-rendering of templates is DOM reconciliation and patching, meaning that only the operations that are needed for us to go from the original DOM tree to the desired DOM tree are performed.
Basic example …
=> feat: Implement DOM reconciliation for templates

packages/client-api/src/providers/glazewm/create-glazewm-provider.ts, packages/desktop/resources/sample-config.yaml, packages/desktop/resources/script.js
The default config for Zebar contains an element that displays the tiling direction for glazewm. Added the `toggle-tiling-direction` command to the glazewm provider and made the button interactive in the sample config.
=> feat: toggle tiling direction on button click in sample config

packages/client-api/src/providers/date/create-date-provider.ts
The `timezone` config property wasn't applied correctly to the `timezone` property, ignoring the value of the `timezone` completely.
[Issue #90](https://github.com/glzr-io/zebar/issues/90)
=> fix: fix `timezone` support of the date provider, closes #90

README.md
The `timezone` and `locale` were missing from the `Date` provider config in the `Readme.md` file
=> docs: Update readme.md to add the date provider's config properties

examples/boilerplate-react-buildless/index.html, examples/boilerplate-solid-ts/src/index.tsx, examples/starter/vanilla.html, examples/starter/with-glazewm.html, examples/starter/with-komorebi.html, packages/client-api/src/providers/battery/create-battery-provider.ts, packages/client-api/src/providers/cpu/create-cpu-provider.ts, packages/client-api/src/providers/create-base-provider.ts, packages/client-api/src/providers/create-provider-group.ts, packages/client-api/src/providers/create-provider.ts, packages/client-api/src/providers/date/create-date-provider.ts, packages/client-api/src/providers/glazewm/create-glazewm-provider.ts, packages/client-api/src/providers/host/create-host-provider.ts, packages/client-api/src/providers/ip/create-ip-provider.ts, packages/client-api/src/providers/keyboard/create-keyboard-provider.ts, packages/client-api/src/providers/komorebi/create-komorebi-provider.ts, packages/client-api/src/providers/memory/create-memory-provider.ts, packages/client-api/src/providers/network/create-network-provider.ts, packages/client-api/src/providers/weather/create-weather-provider.ts, packages/desktop/src/monitor_state.rs, packages/desktop/src/providers/ip/ip_provider.rs, packages/desktop/src/providers/weather/weather_provider.rs
=> feat: change `createProvider` and `createProviderGroup` to resolve immediately

packages/desktop/src/common/length_value.rs, packages/desktop/src/widget_factory.rs
1. Logical needs to be converted into Physical
2. `anchor_<x|y>` ([line 246](https://github.com/glzr-io/zebar/blob/badd5312c9e2e9ea2784bc63902cbd9ec1af4187/packages/desktop/src/widget_factory.rs#L246)) is already a PhysicalPosition 
Monitor: 1600px 900px with 150%
```json
"defaultPlacements": [
{
"anchor": "bottom_left",
"offsetX": "0px",
"offsetY": "-24px",
"width": "100%",
"height": "24px",
"monitorSelection": {
"type": "all"
}
}
]
```
Before the y-position was calculated by  `(1600+-24)*(2/3)` and not by `1600+(-24*(3/2))`.
I think that #115 might be related to this.
=> fix: adjust window position for monitor DPI

examples/boilerplate-react-buildless/styles.css, examples/boilerplate-solid-ts/src/index.css, examples/starter/styles.css
In the examples provided, add `overflow: hidden;` to avoid scrollbars on bar when overflowing.
=> fix: hide overflow in examples

packages/desktop/Cargo.toml, packages/desktop/src/providers/network/wifi_hotspot.rs
Zebar was using `netsh` to get wifi data and then parse it using regex. That lead to some issues (#96) as `netsh` translates the data to the os language.
I have rewritten the whole `wifi_hotspot.rs` file to use the Windows API instead. This should be less error prone, but I had to use some unsafe functions and pointers that needed to be freed. After handling those I don't see any memory leaks in my tests, but it may be worth testing that again. Also, it should work with any Windows version that Tauri works on, but I can only test in Windows 10.
Let me know of any question or suggestion.
Closes #96 
Side note: I have removed the `Win32_System_Threading` feature as it doesn't seem to be used anywhere else.
=> fix: get network gateway SSID and signal strength using Windows APIs

packages/client-api/src/providers/create-provider.ts, packages/client-api/src/providers/disk/create-disk-provider.ts, packages/client-api/src/providers/disk/disk-provider-types.ts, packages/client-api/src/providers/index.ts, packages/desktop/src/providers/disk/disk_provider.rs, packages/desktop/src/providers/disk/mod.rs, packages/desktop/src/providers/mod.rs, packages/desktop/src/providers/provider_config.rs, packages/desktop/src/providers/provider_manager.rs, packages/desktop/src/providers/provider_output.rs, packages/desktop/src/providers/provider_ref.rs
This PR adds a widget for disk information, uses the `sysinfo` package that is already included within.
=> feat: add `disk` provider

examples/starter/with-glazewm.html
Using the glazewm example config, one can now click on the binding mode button to disable the mode again.
This is very useful, if a binding mode was not set correctly and there is no way to disable this (or you just forgot the shortcut).
=> feat: add binding mode toggle to example glazewm config

README.md, examples/boilerplate-react-buildless/index.html, examples/boilerplate-solid-ts/src/index.tsx, packages/client-api/src/desktop/desktop-commands.ts, packages/client-api/src/providers/audio/audio-provider-types.ts, packages/client-api/src/providers/audio/create-audio-provider.ts, packages/client-api/src/providers/media/create-media-provider.ts, packages/desktop/src/common/windows/com.rs, packages/desktop/src/common/windows/mod.rs, packages/desktop/src/providers/audio/audio_provider.rs, packages/desktop/src/providers/provider.rs, packages/desktop/src/providers/provider_function.rs, packages/desktop/src/providers/provider_manager.rs
=> feat: add recording devices and `setVolume` to `audio` provider

CONTRIBUTING.md, package.json, packages/client-api/package.json, packages/desktop/package.json, packages/settings-ui/package.json
Adds `pnpm dev:local`.  Uses local config instead of `/examples/` config.
=> chore: add `dev:local` npm command

packages/client-api/package.json, packages/client-api/src/providers/glazewm/create-glazewm-provider.ts, packages/client-api/src/providers/glazewm/glazewm-provider-types.ts, pnpm-lock.yaml
Exposing the paused state, introduced in glazewm here: https://github.com/glzr-io/glazewm/pull/828
Depends on the this glazewm-js PR: https://github.com/glzr-io/glazewm-js/pull/15
=> feat: expose whether WM is paused in `glazewm` provider

examples/starter/styles.css
This update adds system theme synchronization to zebar using the CSS media query prefers-color-scheme.
Now, zebar will automatically adapt to your operating system's light or dark mode — no manual toggling required.
- Replaced hardcoded colors with CSS variables.
- Introduced media queries for `prefers-color-scheme: light` and `prefers-color-scheme: dark`.
- Added new CSS variables for:
- `--text-size`
- `--icon-size`
- Making it easier to adjust font and icon sizes independently.
- The interface now updates automatically with system theme changes.
As a Windows 11 user with [auto dark mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode?tab=readme-ov-file) based on sunset/sunrise, I’ve always found it frustrating that the default zebar preset didn’t follow the system theme.
This …
=> feat: add auto dark/light theme support to starter config via `prefers-color-scheme`

packages/client-api/src/desktop/desktop-commands.ts, packages/client-api/src/providers/audio/audio-provider-types.ts, packages/client-api/src/providers/audio/create-audio-provider.ts, packages/desktop/src/providers/audio/audio_provider.rs, packages/desktop/src/providers/provider_function.rs
Audio provider currently does not provide a way to mute, which is bugged behaviour since a volume of 0 is still audible. This PR addresses https://github.com/glzr-io/zebar/issues/179.
=> feat: add `isMuted` state and `setMute` to audio provider

Cargo.lock, examples/starter/vanilla.html, examples/starter/with-glazewm.html, examples/starter/with-komorebi.html, packages/client-api/src/providers/network/network-provider-types.ts, packages/desktop/Cargo.toml, packages/desktop/src/providers/network/netdev_res.rs
1. fixed display of network icon when connected to a proprietary VPN such as Proton VPN, now default displays lock shield icon from nerd fonts and updated netdev dependency to version 0.33
2. i updated the 3 examples/starter html files also to add the vpn icon functionality to the examples. 
3. this addresses issue #199 and potentially #159.
4. i did not see any other additional errors or warnings after making these adjustments and confirmed that the other network icons are still functional.
5. this is my first PR ever, so feedback is welcomed. thank you to the team that created zebar and glazewm, they are both awesome!
=> fix: network icon functionality with proprietary vpn clients

crates/systray-util/src/util.rs
Noticed there's an issue with transparency handling of old-school mask-based icons if there is a full black color involved.
In the original code if all the color channels are 0 (full black) it was treated as transparent which is incorrect.
I feel like removing this check will be a better option since we already establishing that we are dealing with mask-based icons beforehand with another check and there's only two possible values for those pixels - fully transparent (255) or opaque (everything else).
Before:
After:
Windows systray:
=> fix: handle transparency in mask-based icons for systray provider

packages/desktop/src/main.rs, packages/desktop/src/providers/keyboard/keyboard_provider.rs, packages/desktop/src/sys_tray.rs
Attempts to fix keyboard provider showing stale values occasionally.
=> fix: stale layout values for keyboard provider

packages/client-api/src/providers/glazewm/glazewm-provider-types.ts
Duplicate of #204 by @nullgato
=> fix: add missing `isPaused` to type definition of `GlazeWmOutput`
